### ISSUE TITLE
OverflowException smart blobbing stereo audio clips

### ISSUE THREAD

**Issue by Omegastick** [Dreaming381/Latios-Framework#8] opened 2022-06-28 19:28 UTC
I get an overflow exception running the `MyriLooped` example scene in Unity `2020.3.34f1` with Unity.Entities `0.51.0-preview.32`. Here's the error:
```
OverflowException
Latios.Authoring.Systems.SmartBlobberConversionSystem`4[TBlobType,TManagedInputType,TUnmanagedConversionType,TContextType].OnUpdate () (at Library/PackageCache/com.latios.latiosframework@150d34a0d6/Core/Core/Authoring/SmartBlobberConversionSystemImpl.cs:470)
Unity.Entities.ComponentSystem.Update () (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities/ComponentSystem.cs:114)
Unity.Entities.ComponentSystemGroup.UpdateAllSystems () (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities/ComponentSystemGroup.cs:583)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Unity.Entities.Conversion.JournalingUnityLogger:LogException(Exception, Object) (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities.Hybrid/GameObjectConversion/JournalingUnityLogger.cs:50)
UnityEngine.Debug:LogException(Exception)
Unity.Debug:LogException(Exception) (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities/Stubs/Unity/Debug.cs:19)
Unity.Entities.ComponentSystemGroup:UpdateAllSystems() (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities/ComponentSystemGroup.cs:588)
Unity.Entities.ComponentSystemGroup:OnUpdate() (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities/ComponentSystemGroup.cs:523)
Unity.Entities.ComponentSystem:Update() (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities/ComponentSystem.cs:114)
Unity.Entities.ComponentSystemGroup:UpdateAllSystems() (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities/ComponentSystemGroup.cs:583)
Unity.Entities.ComponentSystemGroup:OnUpdate() (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities/ComponentSystemGroup.cs:523)
Unity.Entities.ComponentSystem:Update() (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities/ComponentSystem.cs:114)
Unity.Entities.GameObjectConversionUtility:Convert(World) (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities.Hybrid/GameObjectConversion/GameObjectConversionUtility.cs:144)
Unity.Entities.ConvertToEntitySystem:Convert() (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities.Hybrid/ConvertToEntity.cs:176)
Unity.Entities.ConvertToEntitySystem:OnUpdate() (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities.Hybrid/ConvertToEntity.cs:67)
Unity.Entities.ComponentSystem:Update() (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities/ComponentSystem.cs:114)
Unity.Entities.ComponentSystemGroup:UpdateAllSystems() (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities/ComponentSystemGroup.cs:583)
Unity.Entities.ComponentSystemGroup:OnUpdate() (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities/ComponentSystemGroup.cs:523)
Unity.Entities.InitializationSystemGroup:OnUpdate() (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities/DefaultWorld.cs:28)
Unity.Entities.ComponentSystem:Update() (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities/ComponentSystem.cs:114)
Unity.Entities.DummyDelegateWrapper:TriggerUpdate() (at Library/PackageCache/com.unity.entities@0.51.0-preview.32/Unity.Entities/ScriptBehaviourUpdateOrder.cs:426)
```

Debugging this, it seems like it happens when smart blobbing stereo audio clips. Ticking `Force To Mono` on the audio clip asset prevents the error.

**Comment by Dreaming381** [comment] 2022-06-29 00:06
Hi! Thanks for the report!

Unfortunately I have a stupid habit of mis-typing rethrowing of exceptions in C# (C++ habit). If you are able, could you modify the package locally and change SmartBlobberConversionSystemImpl.cs line 470 to read `throw;` instead of `throw e;` and then verify the issue is line 142 of AudioClipSmartBlobberSystem.cs?

Otherwise I will have a fix for that bug this weekend, but that likely won't resolve your issue.

I suspect it is one of two issues. Either you have a very large number of long audio clips that you are trying to convert at once, or you have a bunch of the same audio source in a subscene and the deduplicator isn't working correctly. Can you tell me what kind of scene you are converting clips for? How many clips? How many game objects with each clip? How long is each clip? What is the sample rate of the clips?

**Comment by Omegastick** [comment] 2022-06-29 17:06
Great, thanks for the fix. Feel free to close this issue when you release it.

That's good to know about stereo audio. That should work fine for my use cases.

**Comment by Dreaming381** [comment] 2022-07-04 06:08
Released. Closing.

**Closed by Dreaming381** 2022-07-04 06:08 UTC
