### ISSUE TITLE
[Question] Kinemation Lost support for exposed bones. Bug or by design?

### ISSUE THREAD

**Issue by gabrieldechichi** [Dreaming381/Latios-Framework#23] opened 2022-12-21 19:37 UTC
DMotion has an example for attached objects. It's done in the following way:

- Expose the right hand bone in an _optimized skeleton_
- Parent a sword object to the exposed bone in the scene

This stopped working on Latios 0.6.3. Now the sword gets moved to the root position and doesn't move with the hand.

It does work if the _entire skeleton is not optimized_ though. So not sure if it breaking now is a bug, or if what I did was never supported in the first place.

Here's a video:

https://user-images.githubusercontent.com/15620434/208988803-35da3f69-c88b-4e0b-8f02-6f591578a699.mp4

**Comment by Dreaming381** [comment] 2022-12-21 20:48
That's definitely a bug. Something really bad is happening for you. It is weird, because I have a stress test character with a sword that uses optimized hierarchy with multiple meshes, and I have many instances created. I will try to reproduce this and the other issue you brought to my attention.

Thanks for reporting!

**Comment by gabrieldechichi** [comment] 2022-12-21 21:52
Ok - that's helpful info. I now tried instantiating the entities using a system, and it did fix Issue #21 (exception for multiple entities of same model), so likely the bug is related to having multiple objects of the same SkinnedMesh present in a subscene. The attached object issue wasn't fixed though.

If it helps, the model used in the examples is under `~Samples/Common/Art/Models/LowPolyRobot/LowPolyRobot.fbx` in the [v0.4.0 branch](https://github.com/gamedev-pro/dmotion/tree/feature/v0.4.0).

Thanks for the quick reply!

**Comment by Dreaming381** [comment] 2022-12-23 02:16
Turns out that when you specify an entity to override transforms, any children will adopt its parent's children instead. Anyways, I got a fix.

Replace SetupExportedBonesSystem.cs with the following:
```csharp
using Unity.Burst;
using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Jobs;
using Unity.Transforms;

using static Unity.Entities.SystemAPI;

namespace Latios.Kinemation.Authoring.Systems
{
    [RequireMatchingQueriesForUpdate]
    [DisableAutoCreation]
    [BurstCompile]
    public partial struct SetupExportedBonesSystem : ISystem
    {
        [BurstCompile]
        public void OnCreate(ref SystemState state)
        {
        }

        [BurstCompile]
        public void OnDestroy(ref SystemState state)
        {
        }

        [BurstCompile]
        public void OnUpdate(ref SystemState state)
        {
            var transformComponentsToRemove = new ComponentTypeSet(ComponentType.ReadWrite<Translation>(),
                                                                   ComponentType.ReadWrite<Rotation>(),
                                                                   ComponentType.ReadWrite<NonUniformScale>());
            var componentsToAdd = new ComponentTypeSet(ComponentType.ReadWrite<Parent>(),
                                                       ComponentType.ReadWrite<LocalToParent>(),
                                                       ComponentType.ReadWrite<LocalToWorld>(),
                                                       ComponentType.ReadWrite<CopyLocalToParentFromBone>(),
                                                       ComponentType.ReadWrite<BoneOwningSkeletonReference>());
            var componentsToRemove = new ComponentTypeSet(ComponentType.ReadWrite<CopyLocalToParentFromBone>(),
                                                          ComponentType.ReadWrite<BoneOwningSkeletonReference>());

            new ClearJob().ScheduleParallel();

            var boneCount                 = new NativeReference<int>(Allocator.TempJob, NativeArrayOptions.ClearMemory);
            var rechildHashSet            = new NativeParallelHashSet<Entity>(1, Allocator.TempJob);
            new CountBonesJob { boneCount = boneCount }.Schedule();
            state.Dependency              = new ResizeHashsetJob { boneCount = boneCount, bonesToReChild = rechildHashSet}.Schedule(state.Dependency);

            var ecbAdd                          = new EntityCommandBuffer(Allocator.TempJob);
            var skeletonReferenceLookup         = GetComponentLookup<BoneOwningSkeletonReference>(false);
            var copyLocalToParentFromBoneLookup = GetComponentLookup<CopyLocalToParentFromBone>(false);
            var localToParentLookup             = GetComponentLookup<LocalToParent>(false);
            var parentLookup                    = GetComponentLookup<Parent>(false);
            new ApplySkeletonsToBonesJob
            {
                bonesToReChild                  = rechildHashSet.AsParallelWriter(),
                componentTypesToAdd             = componentsToAdd,
                componentTypesToRemove          = transformComponentsToRemove,
                ecb                             = ecbAdd.AsParallelWriter(),
                skeletonReferenceLookup         = skeletonReferenceLookup,
                copyLocalToParentFromBoneLookup = copyLocalToParentFromBoneLookup,
                localToParentLookup             = localToParentLookup,
                parentLookup                    = parentLookup
            }.ScheduleParallel();

            var ecbRemove                        = new EntityCommandBuffer(Allocator.TempJob);
            new RemoveDisconnectedBonesJob { ecb = ecbRemove.AsParallelWriter(), componentTypesToRemove = componentsToRemove }.ScheduleParallel();

            new ReChildExportedBonesJob { bonesToRechild = rechildHashSet }.ScheduleParallel();

            state.CompleteDependency();

            ecbAdd.Playback(state.EntityManager);
            ecbRemove.Playback(state.EntityManager);

            ecbAdd.Dispose();
            ecbRemove.Dispose();
            boneCount.Dispose();
            rechildHashSet.Dispose();
        }

        [WithOptions(EntityQueryOptions.IncludeDisabledEntities | EntityQueryOptions.IncludePrefab)]
        [WithAll(typeof(CopyLocalToParentFromBone))]
        [BurstCompile]
        partial struct ClearJob : IJobEntity
        {
            public void Execute(ref BoneOwningSkeletonReference boneReference)
            {
                boneReference.skeletonRoot = Entity.Null;
            }
        }

        [WithOptions(EntityQueryOptions.IncludeDisabledEntities | EntityQueryOptions.IncludePrefab)]
        [BurstCompile]
        partial struct CountBonesJob : IJobEntity
        {
            public NativeReference<int> boneCount;

            public void Execute(in DynamicBuffer<OptimizedSkeletonExportedBone> bones)
            {
                boneCount.Value += bones.Length;
            }
        }

        [BurstCompile]
        partial struct ResizeHashsetJob : IJob
        {
            [ReadOnly] public NativeReference<int> boneCount;
            public NativeParallelHashSet<Entity>   bonesToReChild;

            public void Execute()
            {
                bonesToReChild.Capacity = boneCount.Value * 2;
            }
        }

        [WithOptions(EntityQueryOptions.IncludeDisabledEntities | EntityQueryOptions.IncludePrefab)]
        [BurstCompile]
        partial struct ApplySkeletonsToBonesJob : IJobEntity
        {
            [NativeDisableParallelForRestriction] public ComponentLookup<CopyLocalToParentFromBone>   copyLocalToParentFromBoneLookup;
            [NativeDisableParallelForRestriction] public ComponentLookup<BoneOwningSkeletonReference> skeletonReferenceLookup;
            [NativeDisableParallelForRestriction] public ComponentLookup<LocalToParent>               localToParentLookup;
            [NativeDisableParallelForRestriction] public ComponentLookup<Parent>                      parentLookup;
            public NativeParallelHashSet<Entity>.ParallelWriter                                       bonesToReChild;
            public EntityCommandBuffer.ParallelWriter                                                 ecb;
            public ComponentTypeSet                                                                   componentTypesToAdd;
            public ComponentTypeSet                                                                   componentTypesToRemove;

            public void Execute(Entity entity, [ChunkIndexInQuery] int chunkIndexInQuery, in DynamicBuffer<OptimizedSkeletonExportedBone> bones,
                                in DynamicBuffer<OptimizedBoneToRoot> boneToRoots)
            {
                foreach (var bone in bones)
                {
                    if (copyLocalToParentFromBoneLookup.HasComponent(bone.boneEntity))
                    {
                        skeletonReferenceLookup[bone.boneEntity]         = new BoneOwningSkeletonReference { skeletonRoot = entity };
                        copyLocalToParentFromBoneLookup[bone.boneEntity]                                                  = new CopyLocalToParentFromBone {
                            boneIndex                                                                                     = (short)bone.boneIndex
                        };
                        localToParentLookup[bone.boneEntity] = new LocalToParent {
                            Value                            = boneToRoots[bone.boneIndex].boneToRoot
                        };
                        parentLookup[bone.boneEntity] = new Parent { Value = entity };
                    }
                    else
                    {
                        ecb.RemoveComponent(chunkIndexInQuery, bone.boneEntity, componentTypesToRemove);
                        ecb.AddComponent( chunkIndexInQuery, bone.boneEntity, componentTypesToAdd);
                        ecb.SetComponent(chunkIndexInQuery, bone.boneEntity, new BoneOwningSkeletonReference { skeletonRoot = entity });
                        ecb.SetComponent(chunkIndexInQuery, bone.boneEntity, new CopyLocalToParentFromBone { boneIndex      = (short)bone.boneIndex });
                        ecb.SetComponent(chunkIndexInQuery, bone.boneEntity, new LocalToParent { Value                      = boneToRoots[bone.boneIndex].boneToRoot });
                        ecb.SetComponent(chunkIndexInQuery, bone.boneEntity, new Parent { Value                             = entity });
                    }
                    bonesToReChild.Add(bone.boneEntity);
                }
            }
        }

        [WithOptions(EntityQueryOptions.IncludeDisabledEntities | EntityQueryOptions.IncludePrefab)]
        [WithAll(typeof(CopyLocalToParentFromBone))]
        [BurstCompile]
        partial struct RemoveDisconnectedBonesJob : IJobEntity
        {
            public EntityCommandBuffer.ParallelWriter ecb;
            public ComponentTypeSet                   componentTypesToRemove;

            public void Execute(Entity entity, [ChunkIndexInQuery] int chunkIndexInQuery, ref BoneOwningSkeletonReference boneReference)
            {
                if (boneReference.skeletonRoot == Entity.Null)
                    ecb.RemoveComponent(chunkIndexInQuery, entity, componentTypesToRemove);
            }
        }

        [WithChangeFilter(typeof(TransformAuthoring), typeof(Parent))]
        [WithOptions(EntityQueryOptions.IncludeDisabledEntities | EntityQueryOptions.IncludePrefab)]
        [BurstCompile]
        partial struct ReChildExportedBonesJob : IJobEntity
        {
            [ReadOnly] public NativeParallelHashSet<Entity> bonesToRechild;

            public void Execute(ref Parent parent, in TransformAuthoring ta)
            {
                if (ta.AuthoringParent != ta.RuntimeParent && bonesToRechild.Contains(ta.AuthoringParent))
                    parent.Value = ta.AuthoringParent;
            }
        }
    }
}
```

**Comment by gabrieldechichi** [comment] 2022-12-23 04:44
Thanks, that fixed it!

Do you plan to have a minor version release with those bug fixes before 0.7? If so I'll wait for it to release DMotion 0.4, so I don't have to point users to my fork.

**Comment by gabrieldechichi** [comment] 2022-12-23 04:51
This one doesn't seem to have fixed it. I still have the sword in the root and not moving with the exposed bone.

Other things I notice:

- If I manually change the local position, the sword seems to update (it doesn't follow the bone though)
- It happens whether I install `ImprovedTransforms` or not.
- If I place the sword at the same level as the root of the skeleton, it breaks skinning (probably a different, lower priority bug, but wanted to raise it still)

https://user-images.githubusercontent.com/15620434/209272915-93520d4d-ed60-4367-aad6-b2f74856b0a0.mp4

**Comment by Dreaming381** [comment] 2022-12-23 06:19
This was the test scene I put together to try and fix these issues.
![image](https://user-images.githubusercontent.com/25555355/209280907-3b2fcfb1-68aa-4470-bffe-ea2158300ca9.png)
You'll notice I have the subscene closed, but have selected an entity in the entity inspector and it is highlighted in the scene. And on the right, you can see it has zero local translation. Prior to the fix I posted, the capsule snapped to the origin, and when looking at the entity inspector, I realized that the capsule was parented to the skeleton rather than the hand bone.

So check what components are on the exported bone. Make sure it has the proper bone components. Then check what components are on the sword. Make sure it is parented correctly.

I will investigate the other issue you presented where the child of the skeleton breaks skinning. That shouldn't happen either.

**Comment by Dreaming381** [comment] 2022-12-23 21:20
Alright. I have a fix for parenting non-bones to the Animator GameObject. Same file:
```csharp
using Unity.Burst;
using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Jobs;
using Unity.Mathematics;
using Unity.Transforms;

using static Unity.Entities.SystemAPI;

namespace Latios.Kinemation.Authoring.Systems
{
    [RequireMatchingQueriesForUpdate]
    [DisableAutoCreation]
    [BurstCompile]
    public partial struct SetupExportedBonesSystem : ISystem
    {
        [BurstCompile]
        public void OnCreate(ref SystemState state)
        {
        }

        [BurstCompile]
        public void OnDestroy(ref SystemState state)
        {
        }

        [BurstCompile]
        public void OnUpdate(ref SystemState state)
        {
            var transformComponentsToRemove = new ComponentTypeSet(ComponentType.ReadWrite<Translation>(),
                                                                   ComponentType.ReadWrite<Rotation>(),
                                                                   ComponentType.ReadWrite<NonUniformScale>());
            var componentsToAdd = new ComponentTypeSet(ComponentType.ReadWrite<Parent>(),
                                                       ComponentType.ReadWrite<LocalToParent>(),
                                                       ComponentType.ReadWrite<LocalToWorld>(),
                                                       ComponentType.ReadWrite<CopyLocalToParentFromBone>(),
                                                       ComponentType.ReadWrite<BoneOwningSkeletonReference>());
            var componentsToRemove = new ComponentTypeSet(ComponentType.ReadWrite<CopyLocalToParentFromBone>(),
                                                          ComponentType.ReadWrite<BoneOwningSkeletonReference>());

            new ClearJob().ScheduleParallel();

            var boneCount                 = new NativeReference<int>(Allocator.TempJob, NativeArrayOptions.ClearMemory);
            var rechildHashSet            = new NativeParallelHashSet<Entity>(1, Allocator.TempJob);
            new CountBonesJob { boneCount = boneCount }.Schedule();
            state.Dependency              = new ResizeHashsetJob { boneCount = boneCount, bonesToReChild = rechildHashSet}.Schedule(state.Dependency);

            var ecbAdd                          = new EntityCommandBuffer(Allocator.TempJob);
            var skeletonReferenceLookup         = GetComponentLookup<BoneOwningSkeletonReference>(false);
            var copyLocalToParentFromBoneLookup = GetComponentLookup<CopyLocalToParentFromBone>(false);
            var localToParentLookup             = GetComponentLookup<LocalToParent>(false);
            var parentLookup                    = GetComponentLookup<Parent>(false);
            new ApplySkeletonsToBonesJob
            {
                bonesToReChild                  = rechildHashSet.AsParallelWriter(),
                componentTypesToAdd             = componentsToAdd,
                componentTypesToRemove          = transformComponentsToRemove,
                ecb                             = ecbAdd.AsParallelWriter(),
                skeletonReferenceLookup         = skeletonReferenceLookup,
                copyLocalToParentFromBoneLookup = copyLocalToParentFromBoneLookup,
                localToParentLookup             = localToParentLookup,
                parentLookup                    = parentLookup,
                transformAuthoringLookup        = GetComponentLookup<TransformAuthoring>(true)
            }.ScheduleParallel();

            var ecbRemove                        = new EntityCommandBuffer(Allocator.TempJob);
            new RemoveDisconnectedBonesJob { ecb = ecbRemove.AsParallelWriter(), componentTypesToRemove = componentsToRemove }.ScheduleParallel();

            new ReChildExportedBonesJob { bonesToRechild = rechildHashSet }.ScheduleParallel();

            state.CompleteDependency();

            ecbAdd.Playback(state.EntityManager);
            ecbRemove.Playback(state.EntityManager);

            ecbAdd.Dispose();
            ecbRemove.Dispose();
            boneCount.Dispose();
            rechildHashSet.Dispose();
        }

        [WithOptions(EntityQueryOptions.IncludeDisabledEntities | EntityQueryOptions.IncludePrefab)]
        [WithAll(typeof(CopyLocalToParentFromBone))]
        [BurstCompile]
        partial struct ClearJob : IJobEntity
        {
            public void Execute(ref BoneOwningSkeletonReference boneReference)
            {
                boneReference.skeletonRoot = Entity.Null;
            }
        }

        [WithOptions(EntityQueryOptions.IncludeDisabledEntities | EntityQueryOptions.IncludePrefab)]
        [BurstCompile]
        partial struct CountBonesJob : IJobEntity
        {
            public NativeReference<int> boneCount;

            public void Execute(in DynamicBuffer<OptimizedSkeletonExportedBone> bones)
            {
                boneCount.Value += bones.Length;
            }
        }

        [BurstCompile]
        partial struct ResizeHashsetJob : IJob
        {
            [ReadOnly] public NativeReference<int> boneCount;
            public NativeParallelHashSet<Entity>   bonesToReChild;

            public void Execute()
            {
                bonesToReChild.Capacity = boneCount.Value * 2;
            }
        }

        [WithOptions(EntityQueryOptions.IncludeDisabledEntities | EntityQueryOptions.IncludePrefab)]
        [BurstCompile]
        partial struct ApplySkeletonsToBonesJob : IJobEntity
        {
            [NativeDisableParallelForRestriction] public ComponentLookup<CopyLocalToParentFromBone>   copyLocalToParentFromBoneLookup;
            [NativeDisableParallelForRestriction] public ComponentLookup<BoneOwningSkeletonReference> skeletonReferenceLookup;
            [NativeDisableParallelForRestriction] public ComponentLookup<LocalToParent>               localToParentLookup;
            [NativeDisableParallelForRestriction] public ComponentLookup<Parent>                      parentLookup;
            public NativeParallelHashSet<Entity>.ParallelWriter                                       bonesToReChild;
            public EntityCommandBuffer.ParallelWriter                                                 ecb;
            public ComponentTypeSet                                                                   componentTypesToAdd;
            public ComponentTypeSet                                                                   componentTypesToRemove;

            [ReadOnly] public ComponentLookup<TransformAuthoring> transformAuthoringLookup;

            public void Execute(Entity entity, [ChunkIndexInQuery] int chunkIndexInQuery, ref DynamicBuffer<OptimizedSkeletonExportedBone> bones,
                                in DynamicBuffer<OptimizedBoneToRoot> boneToRoots)
            {
                for (int i = 0; i < bones.Length; i++)
                {
                    if (bones[i].boneIndex == 0)
                    {
                        // If the exported bone is still parented to the root, it is not actually an exported bone.
                        // We need to set it up like a local transform.
                        var transformAuthoring                                                           = transformAuthoringLookup[bones[i].boneEntity];
                        ecb.AddComponent(chunkIndexInQuery, bones[i].boneEntity, new Translation { Value = transformAuthoring.LocalPosition });
                        ecb.AddComponent(chunkIndexInQuery, bones[i].boneEntity, new Rotation { Value    = transformAuthoring.LocalRotation });
                        ecb.AddComponent(chunkIndexInQuery, bones[i].boneEntity, new Parent { Value      = entity });
                        ecb.AddComponent(chunkIndexInQuery, bones[i].boneEntity, new LocalToParent {
                            Value = float4x4.TRS(transformAuthoring.LocalPosition, transformAuthoring.LocalRotation, transformAuthoring.LocalScale)
                        });
                        ecb.AddComponent(chunkIndexInQuery, bones[i].boneEntity, new LocalToWorld { Value = transformAuthoring.LocalToWorld });

                        if (math.any(transformAuthoring.LocalScale != new float3(1f, 1f, 1f)))
                            ecb.AddComponent(chunkIndexInQuery, bones[i].boneEntity, new NonUniformScale { Value = transformAuthoring.LocalScale });

                        bones.RemoveAt(i);
                        i--;
                    }
                }

                foreach (var bone in bones)
                {
                    if (copyLocalToParentFromBoneLookup.HasComponent(bone.boneEntity))
                    {
                        skeletonReferenceLookup[bone.boneEntity]         = new BoneOwningSkeletonReference { skeletonRoot = entity };
                        copyLocalToParentFromBoneLookup[bone.boneEntity]                                                  = new CopyLocalToParentFromBone {
                            boneIndex                                                                                     = (short)bone.boneIndex
                        };
                        localToParentLookup[bone.boneEntity] = new LocalToParent {
                            Value                            = boneToRoots[bone.boneIndex].boneToRoot
                        };
                        parentLookup[bone.boneEntity] = new Parent { Value = entity };
                    }
                    else
                    {
                        ecb.RemoveComponent(chunkIndexInQuery, bone.boneEntity, componentTypesToRemove);
                        ecb.AddComponent( chunkIndexInQuery, bone.boneEntity, componentTypesToAdd);
                        ecb.SetComponent(chunkIndexInQuery, bone.boneEntity, new BoneOwningSkeletonReference { skeletonRoot = entity });
                        ecb.SetComponent(chunkIndexInQuery, bone.boneEntity, new CopyLocalToParentFromBone { boneIndex      = (short)bone.boneIndex });
                        ecb.SetComponent(chunkIndexInQuery, bone.boneEntity, new LocalToParent { Value                      = boneToRoots[bone.boneIndex].boneToRoot });
                        ecb.SetComponent(chunkIndexInQuery, bone.boneEntity, new Parent { Value                             = entity });
                    }
                    bonesToReChild.Add(bone.boneEntity);
                }
            }
        }

        [WithOptions(EntityQueryOptions.IncludeDisabledEntities | EntityQueryOptions.IncludePrefab)]
        [WithAll(typeof(CopyLocalToParentFromBone))]
        [BurstCompile]
        partial struct RemoveDisconnectedBonesJob : IJobEntity
        {
            public EntityCommandBuffer.ParallelWriter ecb;
            public ComponentTypeSet                   componentTypesToRemove;

            public void Execute(Entity entity, [ChunkIndexInQuery] int chunkIndexInQuery, ref BoneOwningSkeletonReference boneReference)
            {
                if (boneReference.skeletonRoot == Entity.Null)
                    ecb.RemoveComponent(chunkIndexInQuery, entity, componentTypesToRemove);
            }
        }

        [WithChangeFilter(typeof(TransformAuthoring), typeof(Parent))]
        [WithOptions(EntityQueryOptions.IncludeDisabledEntities | EntityQueryOptions.IncludePrefab)]
        [BurstCompile]
        partial struct ReChildExportedBonesJob : IJobEntity
        {
            [ReadOnly] public NativeParallelHashSet<Entity> bonesToRechild;

            public void Execute(ref Parent parent, in TransformAuthoring ta)
            {
                if (ta.AuthoringParent != ta.RuntimeParent && bonesToRechild.Contains(ta.AuthoringParent))
                    parent.Value = ta.AuthoringParent;
            }
        }
    }
}
```

**Comment by gabrieldechichi** [comment] 2022-12-24 21:26
Ok, the bug still happens on my side, but I think I know the root cause now.

It seems that `ICustomBakingBootstrap` is making it so Empty GameObjects (i.e no Authoring Components) are never baked. The reason this created the above mentioned bug for me (weapon attached to exposed bones), is that the root object for my weapon is an empty gameobject with no components.

After debugging it for a bit, the offender is the parameter `bakerTypes`, passed to `BakerDataUtility.OverrideBakers`, at `BakerExposed.cs:29`. It seems it is missing the `DefaultGameObjectBaker` type.

![image](https://user-images.githubusercontent.com/15620434/209450995-19c73173-514c-4302-8b07-11161a9f52fe.png)

![image](https://user-images.githubusercontent.com/15620434/209451172-a05c79c2-afe3-46c2-a85b-dabbf281158f.png)

I fixed this by changing line 91 at `ICustomBakingBoostracp.cs` (this also fixes the attached object issue)

![image](https://user-images.githubusercontent.com/15620434/209451283-c95932cf-0f22-4b7a-9df9-e792df2c1b1e.png)

**Comment by gabrieldechichi** [comment] 2022-12-24 21:53
On another note, the `SetupExportedBonesSystem.cs` you send in [this reply](https://github.com/Dreaming381/Latios-Framework/issues/23#issuecomment-1364342865) seems to include an unsupported hashmap operation (error below). The unmodified version (0.6.3) does not have this problem.

Just wanted to let you know in case you're planning to add this change to a future version.

![image](https://user-images.githubusercontent.com/15620434/209451776-53a728fa-2b7d-4dc7-a4d6-45d6e4401dd3.png)

```
AverageUpdateTime(1000) (23.104s)
---
SetUp : Unhandled log message: '[Exception] Exception: Shrinking a hash map is not supported'. Use UnityEngine.TestTools.LogAssert.Expect
---
Unity.Collections.LowLevel.Unsafe.UnsafeParallelHashMapData.CheckHashMapReallocateDoesNotShrink (Unity.Collections.LowLevel.Unsafe.UnsafeParallelHashMapData* data, System.Int32 newCapacity) (at Library/PackageCache/com.unity.collections@2.1.0-pre.2/Unity.Collections/UnsafeParallelHashMap.cs:386)
Unity.Collections.LowLevel.Unsafe.UnsafeParallelHashMapData.ReallocateHashMap[TKey,TValue] (Unity.Collections.LowLevel.Unsafe.UnsafeParallelHashMapData* data, System.Int32 newCapacity, System.Int32 newBucketCapacity, Unity.Collections.AllocatorManager+AllocatorHandle label) (at Library/PackageCache/com.unity.collections@2.1.0-pre.2/Unity.Collections/UnsafeParallelHashMap.cs:148)
Unity.Collections.LowLevel.Unsafe.UnsafeParallelHashMap`2[TKey,TValue].set_Capacity (System.Int32 value) (at Library/PackageCache/com.unity.collections@2.1.0-pre.2/Unity.Collections/UnsafeParallelHashMap.cs:1125)
Unity.Collections.NativeParallelHashMap`2[TKey,TValue].set_Capacity (System.Int32 value) (at Library/PackageCache/com.unity.collections@2.1.0-pre.2/Unity.Collections/NativeParallelHashMap.cs:165)
Unity.Collections.NativeParallelHashSet`1[T].set_Capacity (System.Int32 value) (at Library/PackageCache/com.unity.collections@2.1.0-pre.2/Unity.Collections/NativeParallelHashSet.cs:62)
Latios.Kinemation.Authoring.Systems.SetupExportedBonesSystem+ResizeHashsetJob.Execute () (at Packages/Latios-Framework/Kinemation/Authoring/BakingSystems/SetupExportedBonesSystem.cs:114)
Unity.Jobs.IJobExtensions+JobStruct`1[T].Execute (T& data, System.IntPtr additionalPtr, System.IntPtr bufferRangePatchData, Unity.Jobs.LowLevel.Unsafe.JobRanges& ranges, System.Int32 jobIndex) (at <07b4fb2b5af74e479c2c24afaabbcaa4>:0)
---
Exception: Shrinking a hash map is not supported
Unity.Collections.LowLevel.Unsafe.UnsafeParallelHashMapData.CheckHashMapReallocateDoesNotShrink (Unity.Collections.LowLevel.Unsafe.UnsafeParallelHashMapData* data, System.Int32 newCapacity) (at Library/PackageCache/com.unity.collections@2.1.0-pre.2/Unity.Collections/UnsafeParallelHashMap.cs:386)
Unity.Collections.LowLevel.Unsafe.UnsafeParallelHashMapData.ReallocateHashMap[TKey,TValue] (Unity.Collections.LowLevel.Unsafe.UnsafeParallelHashMapData* data, System.Int32 newCapacity, System.Int32 newBucketCapacity, Unity.Collections.AllocatorManager+AllocatorHandle label) (at Library/PackageCache/com.unity.collections@2.1.0-pre.2/Unity.Collections/UnsafeParallelHashMap.cs:148)
Unity.Collections.LowLevel.Unsafe.UnsafeParallelHashMap`2[TKey,TValue].set_Capacity (System.Int32 value) (at Library/PackageCache/com.unity.collections@2.1.0-pre.2/Unity.Collections/UnsafeParallelHashMap.cs:1125)
Unity.Collections.NativeParallelHashMap`2[TKey,TValue].set_Capacity (System.Int32 value) (at Library/PackageCache/com.unity.collections@2.1.0-pre.2/Unity.Collections/NativeParallelHashMap.cs:165)
Unity.Collections.NativeParallelHashSet`1[T].set_Capacity (System.Int32 value) (at Library/PackageCache/com.unity.collections@2.1.0-pre.2/Unity.Collections/NativeParallelHashSet.cs:62)
Latios.Kinemation.Authoring.Systems.SetupExportedBonesSystem+ResizeHashsetJob.Execute () (at Packages/Latios-Framework/Kinemation/Authoring/BakingSystems/SetupExportedBonesSystem.cs:114)
Unity.Jobs.IJobExtensions+JobStruct`1[T].Execute (T& data, System.IntPtr additionalPtr, System.IntPtr bufferRangePatchData, Unity.Jobs.LowLevel.Unsafe.JobRanges& ranges, System.Int32 jobIndex) (at <07b4fb2b5af74e479c2c24afaabbcaa4>:0)
```

**Comment by Dreaming381** [comment] 2022-12-25 00:03
Thanks for finding the Baker vs IBaker issue! That change happened between the experimental and beta versions. Normally, I would find that sort of thing by digging through the diffs of the packages. But it has been rather hectic the last month and a half and I missed this one.

As for the hashmap thing, I found that too shortly after posting. I now use math.max(boneCount * 2, bonesToReChild.Capacity).

Once again, sorry for leaving things in such an awful state, and thank you for your patience. Hopefully after the holidays I will be able to get everything back in order.

**Comment by gabrieldechichi** [comment] 2022-12-29 17:49
No worries! Glad I could help solve the issue.

Do you plan to release a version 0.6.4 before 0.7 with those fixes? I can open PRs if it helps.

I have my fork of Latios, but I'd rather not point users to it unless there is a very strong reason to.

**Comment by Dreaming381** [comment] 2022-12-29 21:03
0.6.4 will be out today or tomorrow. Sorry for the wait. I just got back from my holiday trip yesterday and have access to my workstation again. My laptop doesn't have the software I use for creating documentation and release notes, so I wasn't able to cut a release while away.

**Comment by Dreaming381** [comment] 2023-05-29 19:06
Closing as 0.7 is released and this issue may no longer be applicable as the mechanisms behind this feature are a little different. If it is still causing problems, create a new issue.

**Closed by Dreaming381** 2023-05-29 19:06 UTC
